#!/system/bin/sh

np=/system/etc/init.d/hw_ln

mount -o remount,rw /

if [ -e ${np} ]
then
rm /system/etc/init.d/hw_ln
fi

mount -o remount,ro /

(while :
do
    sf=$(service list | grep -c "SurfaceFlinger")

    if [ $sf -eq 1 ]
    then
        service call SurfaceFlinger 1008 i32 1
        break
    else
        sleep 2
    fi
done
) &
