#!/system/bin/sh

np=/vendor/etc/native_packages.zip

mount -o remount,rw /vendor

if [ -e ${np} ]
then
cp /vendor/etc/native_packages.zip /vendor/etc/native_packages.xml
chmod 0644 /vendor/etc/native_packages.xml
rm /vendor/etc/native_packages.zip

rm /vendor/lib/android.hardware.audio.common@2.0-util.so
rm /vendor/lib/android.hardware.audio.common-util.so

fi

mount -o remount,ro /vendor
